# Accessing/changing specific elements,rows,columns,etc

In [2]:
import numpy as np

In [6]:
a = np.array([[1,2,3,4,5,6],[7,8,9,0,11,12]])

In [7]:
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9  0 11 12]]


In [8]:
#get a specific element (r,c)
a[1,4]

11

In [9]:
#get a sepecific row
a[0,:]

array([1, 2, 3, 4, 5, 6])

In [10]:
#get a specific column
a[:0]

array([], shape=(0, 6), dtype=int32)

In [12]:
a[:,0]

array([1, 7])

In [13]:
#startindex:endindex:stepsize
a[0,1:4:2]

array([2, 4])

In [14]:
a[1,4]

11

In [15]:
a[1,4] = 20

In [16]:
a[1,4]

20

In [17]:
a[1,3] = 21
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 21 20 12]]
