# Initializing different types of Array

In [2]:
import numpy as np

In [3]:
#all 0s matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
#all one s
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
#any other number
np .full((2,2),99)

array([[99, 99],
       [99, 99]])

In [6]:
#repeat an array
arr = np.array([[2,3,4,5]])
r1 = np.repeat(arr,3,axis = 0)

print(r1)

[[2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]]
