In [2]:
import numpy as np
a = np.array([1,2,3,4])

In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [7]:
b = np.array([1,0,1,0])

In [8]:
a + b

array([2, 2, 4, 4])

In [9]:
a ** 2

array([ 1,  4,  9, 16])

In [10]:
a ** 3

array([ 1,  8, 27, 64], dtype=int32)

In [11]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [12]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [13]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [17]:
#Linear algebra
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [18]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [20]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [21]:
#Statistics
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.min(stats)

1

In [23]:
np.max(stats)

6

In [24]:
np.sum(stats)

21

In [25]:
#reorgnising arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [30]:
#vertically stacking vectors/matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
#horizontal stacking
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

np.hstack([h1,h2,h1,h2])


array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
#loading data from files
filedata = np.genfromtxt('new.txt',delimiter=',')
filedata.astype('int64')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int64)

In [41]:
#Advanced indexing and boolean masking
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [43]:
filedata[filedata  > 50].astype('int64')

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int64)

In [46]:
#You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7])
a[[1,2,4]]

array([2, 3, 5])