# This is NumPy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]], np.int32)

In [3]:
myarr[0]

array([ 3,  6, 32,  7])

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int32')

In [6]:
myarr[0,2] = 45

In [7]:
myarr

array([[ 3,  6, 45,  7]])

**Array creation : Creation from other Python structures**

In [9]:
listarray = np.array([[0,1,3],[5,7,8],[2,6,1]])

In [10]:
listarray

array([[0, 1, 3],
       [5, 7, 8],
       [2, 6, 1]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.size

9

In [13]:
listarray.shape

(3, 3)

In [14]:
np.array([34,23,23])

array([34, 23, 23])

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,5,15)

In [21]:
lspace

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [22]:
hoho = np.linspace(1,5,4)

In [23]:
hoho

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [24]:
emp = np.empty((4,6))

In [25]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34599604e-307, 1.69120552e-306, 7.56571288e-307],
       [6.23055991e-307, 2.22526399e-307, 6.23053614e-307,
        7.56592338e-307, 1.60216183e-306, 7.56602523e-307],
       [3.56043054e-307, 1.37961641e-306, 2.22518251e-306,
        1.33511969e-306, 6.23036978e-307, 6.23053954e-307],
       [9.34609790e-307, 8.45593934e-307, 9.34600963e-307,
        1.86921143e-306, 6.23061763e-307, 7.23188049e-308]])

In [26]:
arr = np.arange(99)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.shape

(99,)

In [32]:
x = [[1,2,3],[4,5,6,],[7,1,0]]

In [33]:
ar = np.array(x)

In [34]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [35]:
ar.sum(axis=0)

array([12,  8,  9])

In [36]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [37]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [38]:
ar.flat

In [40]:
for item in ar.flat:
    print item

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (3190918292.py, line 2)

In [41]:
ar.ndip

AttributeError: 'numpy.ndarray' object has no attribute 'ndip'

In [42]:
ar.size

9

In [43]:
ar.nbytes

36